### ISSUE TITLE
Troubles installing in Laravel 9

### ISSUE THREAD

**Issue by Pplan47** [MedicOneSystems/livewire-datatables#403] opened 2022-02-24 13:27 UTC
I tried to install livewire-datatables in a new laravel 9 project: 
=>composer require mediconesystems/livewire-datatables
and the result was:

  Problem 1
    - Root composer.json requires mediconesystems/livewire-datatables ^0.6.8 -> satisfiable by mediconesystems/livewire-datatables[v0.6.8].
    - mediconesystems/livewire-datatables v0.6.8 requires illuminate/support ^7.0|^8.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

Then I tried:
=>composer require mediconesystems/livewire-datatables:dev-master --ignore-platform-req=ext-zip
but...

  Problem 1
    - phpoffice/phpspreadsheet[1.18.0, ..., 1.22.0] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - maatwebsite/excel[3.1.0, ..., 3.1.25] require php ^7.0 -> your php version (8.1.3) does not satisfy that requirement.
    - maatwebsite/excel[3.1.26, ..., 3.1.35] require illuminate/support 5.8.*|^6.0|^7.0|^8.0 -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - mediconesystems/livewire-datatables dev-master requires maatwebsite/excel ^3.1 -> satisfiable by maatwebsite/excel[3.1.0, ..., 3.1.x-dev].
    - maatwebsite/excel[3.1.36, ..., 3.1.x-dev] require phpoffice/phpspreadsheet ^1.18 -> satisfiable by phpoffice/phpspreadsheet[1.18.0, ..., 1.22.0].
    - Root composer.json requires mediconesystems/livewire-datatables dev-master -> satisfiable by mediconesystems/livewire-datatables[dev-master].

Please, can you help to resolve the issue?. Thanks in advance.

**Comment by thyseus** [comment] 2022-02-24 13:37
Duplicate of:

https://github.com/MedicOneSystems/livewire-datatables/issues/398

ensure to use `dev-master` and to use the `-W` flag of composer.

@marksalmon could you bump the packagist.org version? 
Alternatively: could you give me the access rights to the packagist.org version so i can be a livewire-datatables maintainer in the future? Thanks !

**Comment by Pplan47** [comment] 2022-02-24 13:48
It works. Thanks a lot!

**Comment by abbasmashaddy72** [comment] 2022-02-28 04:20
Thanks for the Package.

Waiting for the Stable version.

**Comment by thyseus** [comment] 2022-02-28 10:39
@marksalmon i was able to publish a 0.7.0 version at packagist with the existing hook. I try to keep this package maintained as much as possible until you are back/have time again for the package.

**Closed by thyseus** 2022-02-28 10:39 UTC
