### ISSUE TITLE
Delete column momentarily triggering confirmation dialog of last row during page load

### ISSUE THREAD

**Issue by edgrosvenor** [MedicOneSystems/livewire-datatables#24] opened 2020-09-04 15:55 UTC
When I load a page with a delete column, a confirmation dialog momentarily appears as if I'd hit the delete button on the last row of the table. It goes away when the page has fully loaded and the delete button and conformation dialog appear to behave as expected after that. It's as if open is set to true by default and then changed to false when the page finishes loading. 

laravel 7.27.0
livewire 1.3.3
livewire-datatables 0.3.1

**Comment by marksalmon** [comment] 2020-09-04 16:05
Thanks for reporting, I will take a look.

**Comment by marksalmon** [comment] 2020-09-05 00:46
I think I've found the issue.

The delete component (and several other dynamic components) are controlled by Alpine JS. To ensure a smooth experience, make sure you have:

```css
[x-cloak] {
    display: none;
}
```

somewhere in your css. I have that at the bottom of my ```app.css``` file underneath ```@tailwind utilities``` but I think you can put it anywhere. 

I'm 99% sure this is the cause of the problem. As you can see it doesn't happen on https://livewire-datatables.com/deletable.

Closing this now but do let me know if you have any further problems.

😀

**Closed by marksalmon** 2020-09-05 00:46 UTC
Labels: bug

**Comment by edphill** [comment] 2022-04-04 08:31
hi there... ive stuck with the same problem.

**Comment by msf-Tolok** [comment] 2022-05-18 17:00
you must put it in the header of your html
